### ISSUE TITLE
Sacar descripciones de cada tarjeta de la portada de Voluntariado Social

### ISSUE THREAD

**Issue by LeticiaGiac** [RosarioCiudad/democracyos#101]
Sólo dejar el título sobre la imagen. La descripción que se visualice en el espacio de texto de abajo al igual que ocurre en las otras secciones

**Comment by mjlescano** [comment]
@LeticiaGiac Que te parece agregar un "Call to Action" como el de Desafios?:
<img width="375" alt="screen shot 2017-05-09 at 17 50 14" src="https://cloud.githubusercontent.com/assets/558901/25872116/f9d8f800-34df-11e7-88cd-b20b3b679e9f.png">

**Comment by LeticiaGiac** [comment]
Hola Mati,  creo que no me expliqué bien.Con "cada tarjeta" me refiero a cada entrada o publicación de cada organización social de voluntariado O sea me refiero al texto que en este caso dice "señalización, veredas..." Te lo capturo de pp porque no carga ninguna entrada de Voluntariado ahora, entiendo deben estar trabajando ahí.Creo que faltó una coma para que se entienda.  Sacar descripciones de cada tarjeta, de la portada de Voluntariado Social (#101)
O sea solo título del voluntariado debería verse en el cover. 







      De: Matías Lescano <notifications@github.com>
 Para: RosarioCiudad/democracyos <democracyos@noreply.github.com> 
CC: LeticiaGiac <leticiagiac@yahoo.com.ar>; Mention <mention@noreply.github.com>
 Enviado: Martes, 9 de mayo, 2017 17:50:31
 Asunto: Re: [RosarioCiudad/democracyos] Sacar descripciones de cada tarjeta de la portada de Voluntariado Social (#101)
   
@LeticiaGiac Que te parece agregar un "Call to Action" como el de Desafios?:
