### ISSUE TITLE
Prever estilos para destacados y titulos en el gestor de contenidos

### ISSUE THREAD

**Issue by LeticiaGiac** [RosarioCiudad/democracyos#102]
Que permitan unificar los recursos para organizar los textos descriptivos (negritas,  tamaño, según paleta de colores del sitio) cuando se crean post (seguimiento de proyectos, descripciones de voluntariado social, argumentación de consultas, etc.)

**Comment by franciclo** [comment]
Estamos considerando agregar esta funcionalidad para próximas versiones de DemocracyOS. Lo resolveremos aprovechando el editor de texto para modificar el formato del contenido.
