### ISSUE TITLE
[Consultas] No ocultar consultas recién votadas

### ISSUE THREAD

**Issue by mjlescano** [RosarioCiudad/democracyos#103]
Este caso se dá sólamente cuando está el filtro Más Nuevos activo.

**Comment by Annagramma** [comment]
@mjlescano revisemos cómo están funcionando todos los filtros de esta sección.
Ahora cuando está activo Finalizadas, no aparecen consultas:
![image](https://cloud.githubusercontent.com/assets/4205060/26254557/5b5dd9ec-3c8d-11e7-8508-e9d7c30f2b80.png)
Y cuando está activo Abiertas, no aparece la consulta que está abierta:
![image](https://cloud.githubusercontent.com/assets/4205060/26254606/8a30d8fa-3c8d-11e7-9e28-f5e7a75cfa9e.png)

**Comment by franciclo** [comment]
repetida de #85
