### ISSUE TITLE
[Login] Cuando se hace Login con Facebook, no mostrar el header

### ISSUE THREAD

**Issue by Annagramma** [RosarioCiudad/democracyos#113]
Ahora se ve así: 
![image](https://cloud.githubusercontent.com/assets/4205060/26164795/25f1a21e-3b04-11e7-8a96-82caa92624cd.png)

Y distrae al usuario de hacer clic en "Ingresar".

**Comment by franciclo** [comment]
En donde mas habría que ocultar esa navegación?
Posibles secciones:
- [x] Login
- [x] Registro de usuario
- [x] Settings
- [x] Admin
- [x] Notificaciones
