### ISSUE TITLE
Cambiar sección de "burbujas de proyectos" por video explicativo

### ISSUE THREAD

**Issue by Annagramma** [RosarioCiudad/democracyos#19]
Ahora el diseño incluye "burbujas de proyectos"
![image](https://cloud.githubusercontent.com/assets/4205060/20230093/cd005758-a838-11e6-8b57-debb37fba3bf.png)

Se reemplaza esa sección por el video explicativo sobre "Cómo votar".
![image](https://cloud.githubusercontent.com/assets/4205060/20230109/fd08f25c-a838-11e6-98d9-dfa068e3d26d.png)

Y a la derecha queda sección de texto. Ver siguiente issue.

**Comment by franciclo** [comment]
@Annagramma me pasas el link del video?

**Comment by Annagramma** [comment]
no lo tenemos aún, podemos poner uno de prueba?

**Comment by franciclo** [comment]
ok
