### ISSUE TITLE
Corregir correo de contacto en notificación plataforma

### ISSUE THREAD

**Issue by LeticiaGiac** [RosarioCiudad/democracyos#284]
cuando no permite votar por no pertenecer al padrón o por haber votado, da como contacto para consultar sobre el inconveniente el mail erróneo: yoparticipo@rosario.gob.ar y debe aparecer participa@rosario.gob.ar
![para mica](https://user-images.githubusercontent.com/23635359/32553778-90f88dc4-c476-11e7-9988-d35bb473f961.png)

**Comment by franciclo** [comment]
Este mensaje viene desde el sistema de votación de la Municipalidad.
El cambio debe hacerse ahí.
