### ISSUE TITLE
Notificar a los administradores cuando hay comentarios

### ISSUE THREAD

**Issue by mjlescano** [RosarioCiudad/democracyos#48]

**Comment by Annagramma** [comment]
Rosario Participa posee múltiples contactos con los usuarios, a continuación, se detalla las **notificaciones específicas, en orden sugerido de importancia.**

- [x] al registrarse: el usuario registra sus datos en el Sign up y al hacer clic en "Registrarme ahora", recibe un mail. https://staging-rosariociudad.herokuapp.com/signup Objetivo: validar mail
- [x] para recuperar contraseña: https://staging-rosariociudad.herokuapp.com/forgot
- [x] Sumarse al desafío: el usuario cuando se suma a un Desafío recibe un mail (se resuelve con form de la Muni).
- [x] Contactar a una ONG: el usuario recibe un mail con la data de la ONG (se resuelve con el form de la Muni).
- [x] nueva consulta: toda la base de usuarios recibe un mail en el momento de publicarse un topic de la sección Consultas.
- [x] Comentarios: los admin reciben notificación de los comentarios a su mail; los usuarios reciben notificaciones cuando hay respuestas a sus comentarios.
- [ ] cierre de consulta: toda la base de usuarios recibe un mail al momento de cerrar el plazo de la Consulta. Incluye el link a la Consulta.
- [ ] nueva idea: el autor de una idea recibe un mail al publicarse una idea. El mail incluye el link a la idea.
- [ ] Presupuesto Participativo: a toda la base cuando los proyectos cambien de estado (no cuando cambien otros campos).
- [ ] Feedback de satifacción a usuarios 48hs después de su registro. (formulario: https://democracyos.typeform.com/to/F3oBGE)
- [ ] Evolución de apoyos: el autor de una idea recibe un mail semanalmente que le informa la cantidad de apoyos que tiene su idea hasta el momento.

**Comment by franciclo** [comment]
Revisar template de Mailchimp: https://us14.admin.mailchimp.com/templates/edit?id=90713
[RosarioParticipa.zip](https://github.com/RosarioCiudad/democracyos/files/1053051/RosarioParticipa.zip)

**Comment by franciclo** [comment]
Cierro este issue para pasarlo en limpio en otro.
