### ISSUE TITLE
Simplificar presentación del login con Fb 

### ISSUE THREAD

**Issue by Annagramma** [RosarioCiudad/democracyos#55]
Está así:
![image](https://cloud.githubusercontent.com/assets/4205060/20492845/1da09ed4-aff5-11e6-878a-b598e7554609.png)

Eliminar texto que dice "Login con Facebook", dejar solo el botón.

**Comment by franciclo** [comment]
https://github.com/DemocracyOS/democracyos/commit/4a1f6f42a64f7637b02ee4c4096bed3f3fc1b5b7
