### ISSUE TITLE
Si se ponen espacios en el mail durante el ingreso. El mensaje dice "El texto seguido de @ no puede contener ' ' "

### ISSUE THREAD

**Issue by mjlescano** [RosarioCiudad/democracyos#67]
Si se ponen espacios en el mail durante el ingreso "carolinaw  +01@gmail.com" El mensaje dice "El texto seguido de @ no puede contener ' ' ". Tendría que decir que se debe ingresar un mail válido.

**Comment by franciclo** [comment]
https://github.com/DemocracyOS/democracyos/pull/1339
