### ISSUE TITLE
Agregar textos explicativos en formularios del Admin

### ISSUE THREAD

**Issue by mjlescano** [RosarioCiudad/democracyos#86]

**Comment by Annagramma** [comment]
### **Para el admin de Ideas - usuario final**

**Título de la idea**
_Escribí acá el título de tu idea_

**Etiquetas**
_Podés escribir acá las temáticas vinculadas a tu idea. Por ejemplo, "Transporte" o "Medio Ambiente". Escribí cada una y pulsá ENTER para que se convierta en una etiqueta_

**Contenido**
_¿Qué es lo que querés proponer/solucionar? Explicalo de forma simple y breve. ¿Por qué pensás que tu idea es importante para tu distrito? Recordá que este espacio es para ideas que beneficien a todos, los reclamos puntuales los podés hacer en https://www.rosario.gov.ar/web/reclamos_

**Comment by Annagramma** [comment]
En Decide Madrid hay una sección general que explica el proceso:
https://decide.madrid.es/mas-informacion/propuestas
A tener en cuenta!
