### ISSUE TITLE
Actualizar textos en la home

### ISSUE THREAD

**Issue by mjlescano** [RosarioCiudad/democracyos#88]

**Comment by Annagramma** [comment]
Los textos que estén en la home serán los mismos que en los encabezados de cada sección.

**Comment by Annagramma** [comment]
*Cómo podés participar*  

1 - Registrate
Hacé click en Participá, completá el formulario y sé parte de Rosario Participa.

2 - Votá
Opiná, proponé y decidí cómo querés que sea la ciudad. 

3  -Compartí en redes sociales para que más rosarinos puedan aportar sus opiniones.

*Consultas*  
Queremos conocer tu opinión sobre diferentes temas. Elegí la mejor opción para la ciudad. 
[Quiero opinar] 

*Desafíos*
Tenemos desafíos como comunidad y podemos resolverlos juntos.
[Quiero ser parte]

*Ideas*
¿Tenés ideas para mejorar la vida en la ciudad? Compartilas.
[Quiero proponer]

*Presupuesto participativo*
Vos decidís cómo invertir parte del presupuesto de la ciudad. Podés elegir los proyectos que van a cambiar tu barrio y seguir su ejecución.
[Quiero decidir]

*Voluntariado Social*
Muchas organizaciones sociales buscan tu apoyo!
Conocé a quienes trabajan por una ciudad mejor.
Quiero sumarme]

**Comment by Annagramma** [comment]
Ojo que hoy no está la sección Ideas en la home :)
