### ISSUE TITLE
Arreglar el twitter feed de la home

### ISSUE THREAD

**Issue by mjlescano** [RosarioCiudad/democracyos#89]
- [ ] La opción temporal es poner fotos estáticas con links a tweets ya existentes.
- [ ] Cambiar el hashtag

**Comment by Annagramma** [comment]
Tweets desde los cuales podemos tomar imágenes:
https://twitter.com/ArnoldCuratolo/status/802177873662607360
https://twitter.com/Anpecorelli/status/802956130469056512
https://twitter.com/maxi_carbone/status/802984111384035328
https://twitter.com/apurainfo/status/803979078495772672
https://twitter.com/CMDSur/status/861584299325345799
https://twitter.com/RParticipa/status/859421008096374787
https://twitter.com/RParticipa/status/857995078706638852
