### ISSUE TITLE
Actualizar los íconos

### ISSUE THREAD

**Issue by mjlescano** [RosarioCiudad/democracyos#91]
### Consultas
Mostrar sólo una hoja con un tilde centrado, y 3 opciones. Referencia, sin el doblez de hoja:
<img width="105" alt="screen shot 2017-05-02 at 14 31 00" src="https://cloud.githubusercontent.com/assets/558901/25630557/fb42a156-2f43-11e7-98cc-0d8c82382a92.png">

### Desafíos
Cambiar las manitos. @Annagramma consultar por usar un megáfono:
<img width="105" alt="screen shot 2017-05-02 at 14 36 27" src="https://cloud.githubusercontent.com/assets/558901/25630810/c3b1ed9a-2f44-11e7-82db-8150e6413cb2.png">
<img width="119" alt="screen shot 2017-05-02 at 14 36 31" src="https://cloud.githubusercontent.com/assets/558901/25630808/c37d49dc-2f44-11e7-9ba6-25ab065edcd7.png">

### PP
Seria la siguiente referencia con un check
<img width="116" alt="screen shot 2017-05-02 at 14 38 35" src="https://cloud.githubusercontent.com/assets/558901/25630919/1dbc7364-2f45-11e7-89ed-58f53952ed7e.png">

### Voluntariado
Normalizar grosor de las lineas

**Comment by Annagramma** [comment]
Feedback de Rosario para los ícones de "Desafíos": 
"puede ser una brújula, bracito que hace fuerza, cubo mágico."

**Comment by Annagramma** [comment]
Repasar los íconos, ahora en "Ideas" figura el megáfono.

**Consultas**: los papeles con tildes
**Desafíos**: brújula o similar
**Ideas**: lamparita
**Presupuesto**: personitas y decisión
**Voluntariado**: manitos
