### ISSUE TITLE
Re-ordenar sección PP

### ISSUE THREAD

**Issue by mjlescano** [RosarioCiudad/democracyos#97]
- [x] Actualizar Cover con nuevos estilos
- [x] Bajar el filtro de distritos abajo de la Cover
- [x] Mostrar sólo los proyectos ganadores en la primera página
- [x] Agregar share de watsapp en la card
- [x] Cuando dice $0 se "redondea" a $1
- [x] Colores de Estado: Celeste, Naranja y Verde
- [x] Agregar año al topic y mostrar en el topic view
<img width="1196" alt="proyecto-terminado" src="https://cloud.githubusercontent.com/assets/558901/25633155/91179292-2f4c-11e7-9a8d-c2fdf0eb928f.png">

**Comment by Annagramma** [comment]
Los estados, en castellano, serán, en este orden:
Finalizado
En ejecución
Proyectado

Y el orden general es: Proyectos ganadores> Distrito> Estado> Número de proyecto

**Comment by Annagramma** [comment]
Las rayitas de las cards deben quedar del mismo color que los estados.

**Comment by Annagramma** [comment]
- Si es posible, despublicar todo para luego publicar por Admin los ganadores.
